name: Unit and Integration Tests
on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Download dependencies
        run: go mod download

      - name: Run unit and integration tests
        run: go test -race -tags=integration ./...

      - name: Build
        run: go build -v ./cmd/gh

  integration-tests:
    env:
      GH_TOKEN: ${{ github.token }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Build executable
        run: make

      - name: Run attestation command integration tests
        run: |
          attestation_cmd_test_dir="test/integration/attestation-cmd"
          for script in "$attestation_cmd_test_dir"/*.sh; do
            if [ -f "$script" ]; then
              echo "Running $script..."
              bash "$script"
            fi
          done
